version: '3'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: php
        volumes:
            - ./logs/php:/var/log/php
            - ./${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
            - ${SITE_PATH}:/var/www/bitrix
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - mysql
            - memcached
        networks:
            - bitrix
        restart: unless-stopped
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: webserver
        volumes:
            - ./${WEB_SERVER_TYPE}/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./${WEB_SERVER_TYPE}/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./${WEB_SERVER_TYPE}/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ${SITE_PATH}:/var/www/bitrix
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        links:
            - php
        networks: 
            - bitrix
        restart: unless-stopped
    mysql:
        build: ./mysql
        container_name: mysql
        volumes:
            - ./logs/mysql:/var/log/mysql
            - ./data/mysql:/var/lib/mysql
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - bitrix
        restart: unless-stopped
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached
        entrypoint:
            - memcached
            - --memory-limit=512m
            - --max-item-size=10m
        volumes:
            - ./logs/memcached:/var/log/memcached
            - ./data/memcached:/var/lib/memcached
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - bitrix
        restart: unless-stopped
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/8
